# Generated by Django 6.0.2 on 2026-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'core_system_settings',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('EXPORT', 'Export')], db_index=True, max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'core_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_id'], name='core_audit__app_lab_0902b2_idx'), models.Index(fields=['action', 'created_at'], name='core_audit__action_5c03c3_idx'), models.Index(fields=['user_id', 'created_at'], name='core_audit__user_id_d9fe0d_idx'), models.Index(fields=['created_at'], name='core_audit__created_ab8951_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Field Reference',
                'verbose_name_plural': 'Field References',
                'db_table': 'core_field_reference',
                'indexes': [models.Index(fields=['app_label', 'model_name', 'field_name'], name='core_field__app_lab_51d179_idx'), models.Index(fields=['field_name', 'value'], name='core_field__field_n_928109_idx'), models.Index(fields=['app_label', 'model_name', 'field_name', 'is_active'], name='core_field__app_lab_d2c38e_idx')],
                'unique_together': {('app_label', 'model_name', 'field_name', 'value')},
            },
        ),
    ]
