# Generated by Django 6.0.2 on 2026-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('branch_final', models.CharField(max_length=100)),
                ('course_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('course_id', models.CharField(max_length=100, unique=True)),
                ('course_category', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=50)),
                ('part', models.CharField(max_length=50)),
                ('hours', models.PositiveIntegerField()),
                ('credit', models.DecimalField(decimal_places=1, max_digits=4)),
                ('internal_mark', models.PositiveIntegerField()),
                ('external_mark', models.PositiveIntegerField()),
                ('total_mark', models.PositiveIntegerField()),
                ('examiner_type', models.CharField(max_length=50)),
                ('examiner', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Master',
                'verbose_name_plural': 'Course Master',
                'db_table': 'course_master',
                'ordering': ['-id'],
            },
        ),
    ]
