# Generated by Django 5.2.4 on 2026-05-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField(blank=True, null=True)),
                ('program', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=100)),
                ('external_mark', models.CharField(max_length=50)),
                ('examiner_int_ext', models.CharField(max_length=100)),
            ],
        ),
    ]
