# Generated by Django 6.0.2 on 2026-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(help_text='Primary key - must be unique and not empty', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('course_id', models.CharField(max_length=100)),
                ('course_title', models.CharField(default='', max_length=200)),
                ('program', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('external_mark', models.CharField(max_length=50)),
                ('examiner', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
