# Generated by Django 6.0.2 on 2026-06-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('pattern', '0002_alter_questionpatternsection_marks_per_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='examiner',
        ),
        migrations.AddField(
            model_name='course',
            name='pattern',
            field=models.ForeignKey(blank=True, help_text='Question pattern used for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='pattern.questionpattern'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.CharField(blank=True, help_text="Credits (e.g., '3.0', 'N/A')", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='external_mark',
            field=models.CharField(blank=True, help_text="External marks (can be '--' or numeric)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.CharField(blank=True, help_text="Hours (can be '--' or number)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='internal_mark',
            field=models.CharField(blank=True, help_text="Internal marks (can be '--' or numeric)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_mark',
            field=models.CharField(blank=True, help_text="Total marks (can be '--' or numeric)", max_length=20, null=True),
        ),
    ]
