# Generated by Django 6.0.2 on 2026-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='examiner_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='part',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
