# Generated by Django 6.0.2 on 2026-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=10, unique=True)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('program_type', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_category', models.CharField(blank=True, max_length=100, null=True)),
                ('dept_category', models.CharField(blank=True, max_length=100, null=True)),
                ('examiner_type', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_final', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dor', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Master',
                'verbose_name_plural': 'Staff Master',
                'db_table': 'staff_master',
                'ordering': ['-id'],
            },
        ),
    ]
