# Generated by Django 5.2.4 on 2026-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(default='Unknown', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('doj', models.DateField(verbose_name='Date of Joining')),
                ('dor', models.DateField(blank=True, null=True, verbose_name='Date of Relieving')),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_name', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
