# Generated by Django 6.0.2 on 2026-06-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-id'], 'verbose_name': 'Staff Master', 'verbose_name_plural': 'Staff Master'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='serial_no',
        ),
    ]
