# Generated by Django 5.2.4 on 2026-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_remark_staff_slno_staff_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=15),
        ),
    ]
