# Generated by Django 6.0.2 on 2026-06-20 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_code', models.CharField(db_index=True, help_text='Unique pattern code (e.g., PAT-001)', max_length=20, unique=True)),
                ('pattern_name', models.CharField(help_text='Pattern name (e.g., UG Standard Pattern)', max_length=100)),
                ('total_marks', models.PositiveIntegerField(help_text='Total marks for the question paper', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Exam duration in minutes', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Pattern',
                'verbose_name_plural': 'Question Patterns',
                'db_table': 'question_pattern',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['pattern_code'], name='question_pa_pattern_7d8e01_idx'), models.Index(fields=['is_active'], name='question_pa_is_acti_92303a_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionPatternSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Section name (e.g., Section A, Part I)', max_length=50)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Questions'), ('TRUE_FALSE', 'True/False'), ('FITB', 'Fill in the Blanks'), ('MATCHING', 'Matching'), ('SHORT_ANSWER', 'Short Answer'), ('LONG_ANSWER', 'Long Answer'), ('NUMERICAL', 'Numerical Problem'), ('CASE_STUDY', 'Case Study'), ('ASSERTION', 'Assertion & Reasoning'), ('DIAGRAM', 'Diagram Based'), ('CODE', 'Code Writing'), ('PROGRAM', 'Programming Problem')], db_index=True, help_text='Type of questions in this section', max_length=30)),
                ('no_of_questions', models.PositiveIntegerField(help_text='Total number of questions available', validators=[django.core.validators.MinValueValidator(1)])),
                ('questions_to_answer', models.PositiveIntegerField(help_text='Number of questions student must answer', validators=[django.core.validators.MinValueValidator(1)])),
                ('internal_choice', models.BooleanField(default=False, help_text='Whether internal choices are available in this section')),
                ('marks_per_question', models.DecimalField(decimal_places=2, help_text='Marks for each question', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.ForeignKey(help_text='Pattern this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pattern.questionpattern')),
            ],
            options={
                'verbose_name': 'Question Pattern Section',
                'verbose_name_plural': 'Question Pattern Sections',
                'db_table': 'question_pattern_section',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['pattern', 'question_type'], name='question_pa_pattern_96d95f_idx'), models.Index(fields=['question_type'], name='question_pa_questio_b3b998_idx'), models.Index(fields=['is_active'], name='question_pa_is_acti_088a07_idx')],
            },
        ),
    ]
