# Generated by Django 6.0.2 on 2026-06-20 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpatternsection',
            name='marks_per_question',
            field=models.PositiveIntegerField(help_text='Marks for each question', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
