# Generated by Django 6.0.2 on 2026-06-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(db_index=True, help_text='Academic year (e.g., 2025-2026)', max_length=20, unique=True)),
                ('semester', models.CharField(help_text='Academic semester (e.g., Nov26)', max_length=20)),
                ('semester_type', models.CharField(choices=[('ODD', 'Odd Semester'), ('EVEN', 'Even Semester')], db_index=True, help_text='Semester type (Odd or Even)', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this academic year is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_year',
                'ordering': ['-academic_year', '-semester'],
                'indexes': [models.Index(fields=['academic_year', 'is_active'], name='academic_ye_academi_a1142c_idx'), models.Index(fields=['semester_type', 'semester'], name='academic_ye_semeste_2d1e2f_idx'), models.Index(fields=['is_active'], name='academic_ye_is_acti_4a0153_idx')],
                'unique_together': {('academic_year', 'semester')},
            },
        ),
    ]
