# Generated by Django 6.0.2 on 2026-06-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_alter_course_examiner_type_alter_course_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(blank=True, help_text='Upload the syllabus PDF or document', null=True, upload_to='syllabi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course to which this syllabus belongs', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='course.course', to_field='course_code')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabi',
                'db_table': 'syllabus_master',
                'ordering': ['-created_at'],
            },
        ),
    ]
