# Generated by Django 6.0.2 on 2026-06-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_examiner_type_alter_course_part'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(help_text='Course to which this syllabus belongs', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='course.course'),
        ),
    ]
