# Generated by Django 6.0.2 on 2026-06-21 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('course', '0004_alter_course_examiner_type_alter_course_part'),
        ('staff', '0003_alter_staff_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QPSAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', help_text='Current status of the QPS allocation', max_length=20)),
                ('mail_send_date', models.DateField(blank=True, help_text='Date when notification email was sent to QP setter', null=True)),
                ('assigned_date', models.DateField(blank=True, help_text='Date when QPS was officially assigned', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Deadline for QPS submission', null=True)),
                ('submitted_date', models.DateField(blank=True, help_text='Date when QPS was submitted by setter', null=True)),
                ('approved_date', models.DateField(blank=True, help_text='Date when QPS was approved by checker', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_sem', models.ForeignKey(help_text='Academic year and semester', on_delete=django.db.models.deletion.PROTECT, related_name='qps_allocations', to='academic.academicyear')),
                ('checker', models.ForeignKey(blank=True, help_text='User assigned as Checker', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qps_checker_allocations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course for which QPS is being set', on_delete=django.db.models.deletion.PROTECT, related_name='qps_allocations', to='course.course')),
                ('qp_setter', models.ForeignKey(blank=True, help_text='Staff member assigned as Question Paper Setter', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qps_setter_allocations', to='staff.staff')),
            ],
            options={
                'verbose_name': 'QPS Allocation',
                'verbose_name_plural': 'QPS Allocations',
                'db_table': 'qps_allocation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['academic_sem', 'course'], name='qps_allocat_academi_b02b4b_idx'), models.Index(fields=['qp_setter', 'status'], name='qps_allocat_qp_sett_597d85_idx'), models.Index(fields=['checker', 'status'], name='qps_allocat_checker_8c8589_idx'), models.Index(fields=['status'], name='qps_allocat_status_090f92_idx'), models.Index(fields=['assigned_date'], name='qps_allocat_assigne_efa7df_idx'), models.Index(fields=['due_date'], name='qps_allocat_due_dat_801cdf_idx')],
                'unique_together': {('academic_sem', 'course')},
            },
        ),
    ]
